### ISSUE TITLE
Using `aria-label` can break compatibility with 3rd party code

### ISSUE THREAD

**Issue by joankaradimov** [kazzkiq/balloon.css#123]
One example is [dhtmlxGantt](https://github.com/DHTMLX/gantt). A sample of its usage of `aria-label` can be seen [here](https://docs.dhtmlx.com/gantt/samples/01_initialization/01_basic_init.html).

Overriding the default style for `aria-label` potentially makes any 3rd party library that does higher-level rendering incompatible with balloon.css.

**Comment by kazzkiq** [comment]
Balloon.css only "activates" when using both `aria-label` and `data-balloon-pos` attributes. If an element has only `aria-label` it is not impacted.

This behavior solves the issue, no?

**Comment by boris-petrov** [comment]
@kazzkiq - well, for example, you can see in the source [here](https://github.com/kazzkiq/balloon.css/blob/master/src/balloon.scss#L78) that you actually modify `[aria-label]` globally. And it's really easy to check. Open the example in the first post - see how it looks. Then, in it's source, modify the three relative URLs in the beginning to be absolute and then just add the CSS from `balloon.css` and check the result.

I've created a repository [here](https://github.com/boris-petrov/balloon.css-bug) to showcase it. Just download the file and open it in a browser. See how everything is shifted due to conflicting CSS.

**Comment by kazzkiq** [comment]
You're totally right. We still have properties being assigned to every `[aria-label]` element.

**Comment by kazzkiq** [comment]
[`v1.0.2`](https://www.npmjs.com/package/balloon-css) fixes this issue.
