### ISSUE TITLE
Arrow customization

### ISSUE THREAD

**Issue by pablo-sg-pacheco** [kazzkiq/balloon.css#58]
Hello. Congrats and thanks for this amazing plugin.

I've realized you are using svg to create arrows. This is a problem for me because it hinders arrows customizations. I wanted to simply change colors on my site overriding the .min.css and I couldn't do it.

Why don't you use simple borders to make arrows? E.g:

```
.arrow-right {
  width: 0; 
  height: 0; 
  border-top: 6px solid transparent;
  border-bottom: 6px solid transparent;  
  border-left: 6px solid green;
}
```

It would be so much easier to customize colors and everything else.
Do you want help with this?

**Comment by kazzkiq** [comment]
Hey @pablo-pacheco,

You already can change the arrow (and tooltip) color by changing a variable called `balloon-bg` located at the SASS/LESS files.

The downside is that in order to modify that variable you would need to use the SASS/LESS files directly into your project, instead of just importing the generated CSS file.

The reason of using SVG instead of the "triangle technique" was to diferentiate this project from any other implementation of tooltips using that kind of arrow. The "smooth" SVG arrow gives a unique look to Balloon, IMO. 😄

**Comment by pablo-sg-pacheco** [comment]
I would prefer the "triangle technique" because i could customize colors by JavaScript too or with css only, but I see your point.

Glad to know you are from Brazil. Beautiful project man!

If you want some kind of help let me know
See you

**Comment by kazzkiq** [comment]
I believe this would be a cool feature to implement, but for now, I will focus on other urgent bugfixes/enchancements for v0.5.0.

(This issue might be re-opened in the future).
