### ISSUE TITLE
Tooltips in owl carousel items

### ISSUE THREAD

**Issue by tmoutinho** [kazzkiq/balloon.css#63]
Hi, 

Your ballon.css is awsome, i use it a lot, even better than bootstrap.

Today i found that with overflow: hidden; elements it does not work properly. 
I have tried everything that i know, but without any solution, can you help me out?

Thanks in advance,
Tiago

**Comment by kazzkiq** [comment]
Hey @tiago-moutinho, glad you liked it!

Your issue seems to be related to #57. What happens is that once you set `overflow: hidden` on the parent element, its impossible for Balloon.css (child element) to show up. There isn't a property for a child element that can "overpass" the parent `overflow` directive.

This means that the only option you have in this case would be removing `overflow:hidden`, or setting a tooltip programatically (via JavaScript) to the outer element for every slide change.

To change a tooltip programatically, you simply edit the attributes you set in HTML, but now via JavaScript. Example:

```html
<span id="tooltip-1" data-balloon="My awesome tooltip">Hover me!</span>
```

```js
function changeTooltip (tooltipID, text) {
  document.getElementById(tooltipID).setAttribute('data-balloon', text);
}

// Usage:
changeTooltip('tooltip-1', 'New tooltip text here')
```

**Comment by tmoutinho** [comment]
I will check out your suggestion and let you know if it worked. 

Thanks
