### ISSUE TITLE
Remove !important from your balloon.css

### ISSUE THREAD

**Issue by dehghani-mehdi** [kazzkiq/balloon.css#71]
Hi,

I think your should remove `!important` from `balloon.css` and leave fixing possibility issues of bad styles to user, at least for `font-family`.

Thanks.

**Comment by kazzkiq** [comment]
Thats more of a philosophical debate:
#### `Should Just Work` vs `should give me freedom to fix it myself`

The addition of `!important` came from requests in #37. Not sure what's the best approach to make everyone happy.

**Comment by cthedot** [comment]
Can't make everyone happy I guess ;) 

IMHO to "force" people to override something like font-family with !important is quite harsh. 

The example in #37 would IMHO simply work even without !important, why is this needed?

**Comment by kazzkiq** [comment]
To enforce the neutrality of tooltip font styles. Operational System tooltips are usually "style-agnostic", they open the same way regardless of the context they're in. This is what I believe Balloon.css should achieve too.

`!important` is probably the ugliest feature of CSS ever. But sometimes its useful to have a directive like that exactly for cases where you want to make sure style remains the same without outside interference (aka. [CSS Specificity](https://css-tricks.com/specifics-on-css-specificity/)).

**Comment by dehghani-mehdi** [comment]
@kazzkiq thanks for the support,

One possible solution, provide another `css file` (_for example balloon.theme.css_) and move all `!important` rules there, so some users like me can ignore this css file.

**Comment by cthedot** [comment]
I'd use Balloon CSS if I wanted "nice" non system tooltips. Otherwise at least for short tooltips a title would be just fine. I disagree tooltips cannot be nice and should look the same everywhere, color can be styles too, or can it not? 
And as said, the example in #37 would work even if removing the !important, it is simply not needed to override the sites styles as :after if nowhere styled and e.g. a "strong" elements boldness is overwritten with a simple font-weight: normal for :after. Just my 2 cents though

**Comment by seezee** [comment]
+1 for this.

**Comment by handeyeco** [comment]
Just FYI, I was looking at https://kazzkiq.github.io/balloon.css/ and noticed that the Font Awesome example is broken for me (OSX Chrome/Firefox) as it just shows squares rather than icons.

Looking through the code, I think it's because `font-family: sans-serif !important;` is overriding `font-family: FontAwesome;` When I change it to `font-family: FontAwesome !important;` it works as expected.

I was going to file a separate issue/PR, but it seems like it's related to this issue.
