### ISSUE TITLE
Image show in tooltip

### ISSUE THREAD

**Issue by emresaracoglu** [kazzkiq/balloon.css#75]
Hello

I like it this tooltip app, thank you! I have a question. How I can run HTML codes in the Ballon Tooltip?

For example; I want to add image code in the tooltip, it is possible for Ballon.css?

**Comment by kazzkiq** [comment]
Hey @emresaracoglu,

sadly, there is no way to add HTML code inside those tooltips. As far as I known, that's a pseudo-elements specs limitation.

What you can do, however, is add some extra CSS in order to display images in the tooltip. Here is an example using `background-image`:

https://jsfiddle.net/w7um6dvq/

**Comment by emresaracoglu** [comment]
Hello @kazzkiq 

Thank you for your time, also JSFiddle demo :)
if there are more than one button, then how do we do it? 
Can we specify a specific ID and class?

**Comment by kazzkiq** [comment]
Sure! You could create a class like: `.show-image` in all Balloon.css buttons that needs to show images.

Example: https://jsfiddle.net/jv1vsdep/

**Comment by emresaracoglu** [comment]
@kazzkiq , 
do you know?
Youre great man! :)
