### ISSUE TITLE
Using other HTML elements than "button"?

### ISSUE THREAD

**Issue by ghost** [kazzkiq/balloon.css#98]
Hello,

I recently found the project and the main documentation at:

https://kazzkiq.github.io/balloon.css/

There is one thing I'd like to see added there.

- Could the page explain why "button" tag is used?

I tested with "<span>" tag and it seems to work too,
so I wonder if we can use it on any tag.

**Comment by kazzkiq** [comment]
Yes, you can use balloon on any HTML element, as far [as this element accepts :before and :after pseudo elements](https://stackoverflow.com/questions/8621127/list-of-html-elements-that-support-the-css-before-and-after-pseudo-elements).

The reason why `<button>` is used in examples is simply because its meant for user mouse/touch interaction, so it makes more semantic sense to use them as examples instead of `<div>` or other block elements. But it could really be any other element.
